#:schema node_modules/wrangler/config-schema.json
name = "expenditure"
main = "src/index.ts"
compatibility_date = "2024-06-05"


[vars]
API_HOST = "example.com"
API_ACCOUNT_ID = "example_user"
SERVICE_X_DATA = { URL = "service-x-api.dev.example", MY_ID = 123 }
CORS_WHITELIST = [
    "http://localhost:5173"
]